### ISSUE TITLE
Add MU-plugin support

### ISSUE THREAD

**Issue by johnie** [urre/topdash#2]
I'm having trouble activating topdash as a mu-plugin. Would be awesome if you could take a look at it :blush:

**Comment by urre** [comment]
This is [now fixed](https://github.com/urre/topdash/blob/master/topdash.php#L49)

You will have load the plugin from the `/mu-plugins` folder by using a loader php file, and use for example:
`require WPMU_PLUGIN_DIR.'/topdash/topdash.php';`

**Comment by johnie** [comment]
Terrific!
